name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3.4.1

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/awarenesscolor.com/ --name="tobiaswright" --email=tobias@tobiaswright.com
